name: soundx
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  just_audio: ^0.10.4
  audio_session: ^0.2.2
  just_audio_background: ^0.0.1-beta.17
  get_it: ^8.0.3
  injectable: ^2.5.0
  firebase_core: ^3.15.1
  firebase_storage: ^12.4.9
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.30
  lottie: ^3.3.1
  dio: ^5.8.0+1
  firebase_database: ^11.3.9
  widgetbook: ^3.14.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.0
  freezed: ^3.0.0-0.0.dev
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
