name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  soundx:
    path: ../
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  widgetbook_generator: ^3.13.0
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/core/constants/generated/
  # line_length: 80 # Optional

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true # Optional
    outputs: # Optional
      # Set to true if you want this package to be a package dependency
      # See: https://flutter.dev/docs/development/ui/assets-and-images#from-packages
      package_parameter_enabled: false # Optional
      # Available values:
      # - camel-case
      # - snake-case
      # - dot-delimiter
      style: camel-case # Optional
      class_name: AppAssets
    exclude: []


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
